# Generated by Django 5.0.7 on 2024-12-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='listen_to_wakewords',
            field=models.BooleanField(default=False),
        ),
    ]
