# Generated by Django 5.0.7 on 2024-12-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_listen_to_wakewords'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10),
        ),
    ]
